### ISSUE TITLE
Error in samps_list[[which.min(bic_vec)]] : attempt to select less than one element in get1index

### ISSUE THREAD

**Issue by Tato14** [KarchinLab/pictograph#15]
Hi! 

I am getting the title error when tried to run `clusterSep` in my own data. 

I am unsure why this error is happening. If it may help, I am getting a warning once I tried to use `importCSV` regarding variants not present in all the samples (guessing here):

```
Warning message:                                                                                                                                            
In importCSV("./Patient_228481.csv", alt_reads_thresh = 6, vaf_thresh = 0.02) :
  Total read counts of 0 encoutered. Replaced 0 with mean total read count.
```

Could it be the reason that when I run:

```
all_set_results <- clusterSep(input_data,
                              n.iter = 1000, n.burn = 100, thin = 1,
                              one_box = F, mc.cores = 2)
```

I got the subject error?
Thanks

**Comment by jiaying2508** [comment]
Hi! The warning message from importCSV should not matter to the clusterSep function. 

Have you encountered similar issue with other patient or is the error specific to this patient? Is it possible for you to share the data? It is difficult to know the exact problem without using the same input data.

**Comment by Tato14** [comment]
Dear,

I tried different patient samples and I found one that works (most of them don't). Here I attach the files. `Patient 1602547` is the one that works. 

Thanks

[Patient_1602547.csv](https://github.com/KarchinLab/pictograph/files/13407888/Patient_1602547.csv)
[Patient_1916008.csv](https://github.com/KarchinLab/pictograph/files/13407889/Patient_1916008.csv)
[Patient_228481.csv](https://github.com/KarchinLab/pictograph/files/13407890/Patient_228481.csv)

**Comment by jiaying2508** [comment]
Hi,

The problem might be that you didn't set the max_K. I'd recommend to set max_K to 5 or smaller if setting one_box=F. Also since you had so many mutations, I'd recommend to set one_box=T and max_K to 10. Also please try to uninstall and re-install the latest version of the tool using devtools::install_github("KarchinLab/pictograph", build_vignettes = TRUE).

**Comment by Tato14** [comment]
Worked like a charm. Thanks. However, I am running out of memory due to the high number of samples. Could I save the `clusterSep` result in an .Rmd file in order to reduce memory usage?

**Comment by jiaying2508** [comment]
Sure. You can always save the results and reload the data using standard R functions.
