### ISSUE TITLE
multiplicity of a variant

### ISSUE THREAD

**Issue by SebastianHollizeck** [KarchinLab/pictograph#6]
Hi,

thanks a lot for developing this, it looks exactly like something I want to use.

I am slightly unsure what to do for the multiplicity and variant counts

Your example data shows multiplicity of 2 for some variants, but i dont understand how to replicate that with my data

for example, if I have 3 variants present in multiple samples in different amounts e.g.

| Sample  | A>C | A>G | A>T |
| :---: | :---: | :---: | :---: |
|  1  | 5  | 10 |  0 | 
| 2 | 0 | 10 | 0 | 
| 3  | 5  | 5   | 5    | 

would that lead to multiplicity

| Sample1  | Sample 2 | sample 3  |
| :---: | :---: | :---: | 
|  3 | 3 | 3 | 

or 

| Sample1  | Sample 2 | sample 3  |
| :---: | :---: | :---: | 
|  2 | 1 | 3 | 

And for the counts, do I make a new line for each of the variants, or do they get summed up?

so y being

| Sample1  | Sample 2 | sample 3  |
| :---: | :---: | :---: | 
|  5 | 0 | 5 | 
|  10 | 10 | 5 | 
|  0 | 0 | 5 | 

or 

| Sample1  | Sample 2 | sample 3  |
| :---: | :---: | :---: | 
|  15 | 25 | 15 | 

I would love to use this tool i just want to make sure I use it correctly.

Thanks,
Sebastian

**Comment by llyzhng** [comment]
Hi Sebastian, 

The multiplicity is the number of alleles on which a variant is present, so each variant will have its own value and it may different among samples. Multiplicity will always be less than or equal to the total copy number at the locus. 

For the read counts,

**Comment by SebastianHollizeck** [comment]
Thank you for clearing that up, can you suggest a tool/method to estimate multiplicity of a variant? I have local copy number for each variant
